export const personalInfo = {
  name: "Kalyan Pandaga",
  taglines: [
    "Full Stack Developer | MERN & AI Integrations",
    "Building Scalable & High-Performance Web Apps",
    "MERN Stack Specialist | Backend & APIs Expert",
    "Frontend Developer | React, Tailwind, Modern UI",
    "Backend Developer | Node.js, Django, REST APIs",
    "Python & Django Developer with AI Integrations",
    "Passionate about AI-Driven Web Applications",
    "Turning Ideas into Interactive Digital Solutions",
  ],
  intro:
    "Full Stack Developer with 1.6+ years of experience specializing in Python (Django) and the MERN stack. Skilled at building scalable APIs, intuitive frontends, and integrating AI services to create impactful digital products.",
  email: "kalyanlee3@gmail.com",
  resumeUrl: "/kalyan_resume.pdf",
  socialLinks: {
    github: "https://github.com/Kalyanpandaga",
    linkedin: "https://www.linkedin.com/in/kalyan-pandaga",
    email: "mailto:kalyanlee3@gmail.com",
  },
};

export const aboutInfo = {
  description:
    "I’m a results-driven Full Stack Developer with 1.6+ years of professional experience in backend development using Django REST Framework and strong expertise in building modern full stack applications with the MERN stack. My focus is on crafting scalable APIs, seamless user experiences, and AI-powered solutions that solve real-world challenges. Currently, I’m expanding my skills in advanced Node.js, React, and cloud integrations to stay at the forefront of modern web development.",
  experience: "1.6+ years (Backend) | Growing MERN Expertise",
  focus: "Full Stack Development, AI Integrations, Scalable Architectures",
  location: "India",
};

export const skills = {
  frontend: [
    { name: "React", icon: "FaReact" },
    { name: "JavaScript (ES6+)", icon: "FaJs" },
    { name: "HTML5", icon: "FaHtml5" },
    { name: "CSS3", icon: "FaCss3Alt" },
    { name: "Tailwind CSS", icon: "SiTailwindcss" },
    { name: "React Router", icon: "SiReactrouter" },
  ],
  backend: [
    { name: "Node.js", icon: "FaNodeJs" },
    { name: "Express.js", icon: "SiExpress" },
    { name: "Django ", icon: "SiDjango" },
    { name: "REST APIs", icon: "FaServer" },
    { name: "Python", icon: "FaPython" },
    { name: "Socket.io", icon: "SiSocketdotio" },
  ],
  database: [
    { name: "MongoDB", icon: "SiMongodb" },
    { name: "PostgreSQL", icon: "SiPostgresql" },
    { name: "SQLite", icon: "SiSqlite" },
    { name: "Mongoose ODM", icon: "SiMongodb" },
  ],
};

export const timelineData = [
  {
    year: "2013–2015",
    title: "Intermediate (MPC)",
    description: "Secured 90.1%",
    type: "education",
    icon: "graduation",
  },
  {
    year: "2015–2018",
    title: "BSc MPCs",
    description: "Achieved 73%",
    type: "education",
    icon: "graduation",
  },
  {
    year: "2018–2019",
    title: "Computer Operator",
    description: "Sri Chaitanya Junior College (6 months)",
    type: "work",
    icon: "briefcase",
  },
  {
    year: "2019–2022",
    title: "MCA",
    description: "Achieved 76%",
    type: "education",
    icon: "graduation",
  },
  {
    year: "Sep 2022 – Mar 2024",
    title: "SDE-I",
    description: "NxtWave (18 months)",
    type: "work",
    icon: "briefcase",
  },
  {
    year: "2024 – Present",
    title: "Upskilling & Job Search",
    description: "Focusing on MERN stack and AI integrations",
    type: "learning",
    icon: "rocket",
  },
];

export const projects = {
  fullstack: [
    {
      id: 1,
      name: "DevTinder – Developer Networking Platform",
      description:
        "Full-stack web application enabling developers to connect, collaborate, and chat in real time. Features secure authentication, editable profiles, and real-time messaging for seamless networking.",
      features: [
        "Secure user authentication using JWT with HTTP-only cookies (protection against XSS/CSRF)",
        "Editable developer profiles with live preview (name, avatar, bio, age, gender)",
        "Developer feed to discover profiles and send interest/ignore requests",
        "Connection requests management (accept/reject) to establish connections",
        "Real-time one-to-one chat between connected developers using Socket.IO",
        "Responsive UI with React Router and conditional rendering based on auth state",
        "Deployed on Render with backend-frontend integration and CORS handling",
      ],
      techStack: [
        "React (Vite)",
        "Tailwind CSS / DaisyUI",
        "Redux Toolkit",
        "Node.js",
        "Express.js",
        "MongoDB",
        "Mongoose",
        "Socket.IO",
        "JWT (HTTP-only cookies)",
      ],
      category: "fullstack",
      liveUrl: "https://dev-tinder-qyta.onrender.com",
      githubUrl: "https://github.com/Kalyanpandaga/dev_tinder_frontend",
    },
    {
      id: 2,
      name: "Meds Buddy Check – Medication Management System",
      description:
        "A modern medication tracking platform for patients and caretakers. Provides medication scheduling, daily tracking, and progress monitoring through a clean, user-friendly interface.",
      features: [
        "Separate patient and caretaker roles for tailored experiences",
        "Medication scheduling with reminders and daily status tracking",
        "Progress metrics and calendar-based medication history view",
        "Caretaker dashboard for managing multiple patients and assignments",
        "Responsive UI built with React and TypeScript for seamless usage",
      ],
      techStack: [
        "React (Vite + TypeScript)",
        "Tailwind CSS / DaisyUI",
        "Node.js",
        "Express.js",
        "SQLite",
        "JWT Authentication",
      ],
      category: "fullstack",
      liveUrl: "https://meds-buddy-check-app.onrender.com/",
      githubUrl: "https://github.com/Kalyanpandaga/meds-buddy-check",
    },
    {
      id: 3,
      name: "Project Management Tool",
      description:
        "A full-stack project management application with role-based access for Admin, Manager, and Developer roles. Enables project/task management, team assignments, progress tracking, and commenting with a modern React UI and Node.js backend.",
      features: [
        "Role-based access control with Admin, Manager, and Developer permissions",
        "Project management (create, edit, delete, assign team members, track progress)",
        "Task management (create, assign, deadlines, status updates, commenting)",
        "JWT-based authentication stored in cookies for secure login sessions",
        "Dashboard with task counts, overdue tasks, and project completion metrics",
        "API documentation via Swagger UI and Postman collection",
        "Responsive frontend built with React and Tailwind CSS",
      ],
      techStack: [
        "React",
        "Tailwind CSS",
        "Node.js",
        "Express.js",
        "SQLite (Sequelize ORM)",
        "JWT Authentication",
        "Swagger API Docs",
      ],
      category: "fullstack",
      liveUrl: "https://project-management-tool-1-9214.onrender.com",
      githubUrl: "https://github.com/Kalyanpandaga/project-management-tool",
    },
    {
      id: 4,
      name: "Candidates Management System",
      description:
        "A full-stack application to manage candidate records with authentication and protected routes, featuring CRUD operations and filtering capabilities.",
      features: [
        "User registration and login with JWT-based authentication",
        "Protected routes for candidate management (CRUD operations)",
        "Search, filter, and paginate candidates efficiently",
        "Frontend built with React (Vite) and React Router for seamless navigation",
        "Secure backend built with Node.js, Express.js, and MongoDB (Mongoose)",
        "CORS-enabled API for smooth frontend-backend communication",
      ],
      techStack: [
        "React.js",
        "Vite",
        "React Router",
        "Node.js",
        "Express.js",
        "MongoDB",
        "JWT",
        "Cookies API",
        "CSS3",
      ],
      category: "fullstack",
      liveUrl: "https://hr-candidate-manager-dashboard.onrender.com/",
      githubUrl: "https://github.com/Kalyanpandaga/candidate_manager_frontend",
    },
    {
      id: 5,
      name: "Personal Finance Visualizer",
      description:
        "A full-stack finance tracker to record expenses, visualize monthly data with charts, and manage personal budgets using Next.js and MongoDB.",
      features: [
        "Track daily expenses with real-time updates",
        "Visualize monthly finances with interactive bar charts",
        "Securely store data using MongoDB Atlas",
        "Modern UI built with Tailwind CSS and Shadcn UI components",
        "Built with Next.js 14 App Router for optimized performance",
      ],
      techStack: [
        "Next.js 14 (App Router)",
        "React",
        "MongoDB",
        "Mongoose",
        "Tailwind CSS",
        "Shadcn UI",
      ],
      category: "fullstack",
      liveUrl: "https://personal-finance-visualizer-lime.vercel.app",
      githubUrl: "https://github.com/Kalyanpandaga/personal-finance-visualizer",
    },
    {
      id: 6,
      name: "AI Mock Interview Platform",
      description:
        "A comprehensive AI-powered platform for personalized interview practice with real-time question generation, intelligent feedback, and progress tracking.",
      features: [
        "Dynamic interview flow with context-aware AI-generated questions",
        "Real-time analysis and actionable feedback to improve performance",
        "Backend APIs built using Python and Django for secure data handling",
        "User authentication, interview history, and progress tracking",
        "Responsive React frontend with smooth navigation and feedback display",
      ],
      techStack: [
        "Python",
        "Django",
        "REST API",
        "React",
        "AI Services (OpenAI)",
        "HTML",
        "CSS",
      ],
      category: "fullstack",
    },
  ],
  frontend: [
    {
      id: 7,
      name: "JOBBYAPP",
      description:
        "A responsive job search application frontend built with React and Tailwind CSS. Implements secure login, dynamic filters, and job detail views, mimicking real-world job boards with authentication and API integration.",
      features: [
        "JWT authentication with protected routes (Login, Jobs, Job Details)",
        "Dynamic job listing with filters: employment type, salary range, and search",
        "Profile API integration with retry handling for failures",
        "Detailed job view with similar jobs and external company links",
        "Error handling, loading states, and fallback views (No Jobs, Failure pages)",
        "Responsive UI with routing and navigation (Home, Jobs, Not Found pages)",
      ],
      techStack: [
        "React",
        "React Router",
        "CSS",
        "REST API Integration",
        "JWT Authentication",
      ],
      category: "frontend",
      liveUrl: "https://jobbyapp-l536.onrender.com/",
      githubUrl: "https://github.com/Kalyanpandaga/JOBBYAPP",
    },
    {
      id: 8,
      name: "NxtTrendz – E-commerce Clone",
      description:
        "Modern e-commerce web app inspired by Amazon and Flipkart. Features product listing, detailed views, and secure login with JWT authentication, providing a seamless shopping experience.",
      features: [
        "User authentication with JWT and secure data storage in local storage",
        "Dynamic routing for Login, Product Listing, and Product Details pages",
        "REST API integration for fetching product data and managing sessions",
        "Responsive UI styled with Bootstrap and custom CSS",
        "Form validation and error handling for login flow",
        "Authorization-based navigation for protected routes",
      ],
      techStack: [
        "React",
        "JavaScript",
        "Bootstrap",
        "CSS3",
        "React Router",
        "REST APIs",
        "JWT Authentication",
        "Local Storage",
      ],
      category: "frontend",
      liveUrl: "https://nxttrendz-rzws.onrender.com",
      githubUrl: "https://github.com/Kalyanpandaga/nxtTrendz",
    },
    {
      id: 9,
      name: "GitHub User Search",
      description:
        "A modern, responsive React application that allows users to search GitHub profiles and view top repositories with real-time data from the GitHub REST API.",
      features: [
        "Search GitHub users by username with debounced input for performance",
        "Display detailed profile information including avatar, bio, followers, and location",
        "View top 5 repositories sorted by stars with pagination support",
        "Mobile-first responsive UI with dark mode toggle",
        "Graceful error handling and loading states for seamless experience",
      ],
      techStack: [
        "React.js",
        "Vite",
        "Tailwind CSS v4",
        "React Icons",
        "GitHub REST API",
        "Node.js",
      ],
      category: "frontend",
      liveUrl: "https://github-user-search-lilac-three.vercel.app/",
      githubUrl: "https://github.com/Kalyanpandaga/github_user_search",
    },
  ],
  backend: [
    {
      id: 10,
      name: "CrediKhaata – Loan Management System",
      description:
        "Backend-only credit sale and loan management system built with Node.js and MongoDB. Handles user authentication, customer credit tracking, loan creation, repayments, and overdue status management with cron jobs.",
      features: [
        "JWT-based user authentication and role handling (Merchant/Default)",
        "Customer management (create, update, delete, view)",
        "Loan lifecycle: creation, status tracking (PENDING, PAID, OVERDUE)",
        "Repayment management with history and summaries",
        "Automated status updates using cron jobs",
        "Rate-limited endpoints and input validation for security",
      ],
      techStack: [
        "Node.js",
        "Express",
        "MongoDB",
        "Mongoose",
        "JWT Authentication",
        "bcrypt",
        "Node-Cron",
        "Express Rate Limit",
      ],
      category: "backend",
      liveUrl: "",
      githubUrl: "https://github.com/Kalyanpandaga/credikhaata",
    },
    {
      id: 11,
      name: "URL Shortener API",
      description:
        "A minimal and efficient URL shortening service built with Node.js and MongoDB. Provides short links with expiration, redirection, and click tracking features, secured with rate limiting and validation.",
      features: [
        "Generate 6-character short URLs from long URLs",
        "Automatic link expiration and TTL cleanup",
        "Redirect to original URLs via short codes",
        "Click count tracking for analytics",
        "Rate limiting to prevent abuse and spam",
        "Robust URL validation using validator.js",
      ],
      techStack: [
        "Node.js",
        "Express",
        "MongoDB",
        "Mongoose",
        "nanoid",
        "Express Rate Limit",
        "Validator.js",
      ],
      category: "backend",
      liveUrl: "", // Add if deployed
      githubUrl: "https://github.com/Kalyanpandaga/url-shortener",
    },
    {
      id: 12,
      name: "Personal Expense Tracker Backend",
      description:
        "A backend API for tracking personal income and expenses, built with Node.js, Express, Sequelize, and SQLite. Provides secure JWT authentication, transaction management, and financial summaries.",
      features: [
        "JWT-based authentication for secure user access",
        "Manage income and expense transactions with CRUD operations",
        "Transaction summaries with total income, expense, and balance",
        "Pagination support for transaction history",
        "SQLite database integration with Sequelize ORM",
        "RESTful API design for easy frontend integration",
      ],
      techStack: [
        "Node.js",
        "Express.js",
        "Sequelize",
        "SQLite",
        "JWT",
        "dotenv",
      ],
      category: "backend",
      liveUrl: "",
      githubUrl: "https://github.com/Kalyanpandaga/expense-tracker",
    },
    {
      id: 13,
      name: "Web Scraping Assignment Project",
      description:
        "A Python-based assignment project to scrape quotes from a website, store them in an SQLite database, and query the data for insights. Implemented using BeautifulSoup for scraping and SQLite for storage.",
      features: [
        "Scrape quotes, authors, and tags from `quotes.toscrape.com`",
        "Store scraped data in SQLite with normalized schema (Quotes, Authors, Tags tables)",
        "Use foreign keys to maintain relationships between tables",
        "Query database for total quotes, quotes by author, tag statistics, and top authors",
        "Data pipeline split into three modular steps for maintainability",
      ],
      techStack: ["Python", "BeautifulSoup", "SQLite", "Requests"],
      category: "backend",
      liveUrl: "",
      githubUrl:
        "https://github.com/Kalyanpandaga/Web-Scrapping-Assignment-Project",
    },
  ],
};

export const placeholderExampleQuestions = [
  "Why do you have a career gap?",
  "Which is your strongest project?",
  "How many years of React experience do you have?",
  "What technologies do you specialize in?",
  "Tell me about your AI Mock Interview Platform",
  "What makes you different from other developers?",
  "How do you handle challenging projects?",
  "What is your experience with backend development?",
];
