export const personalInfo = {
  name: "Kalyan Pandaga",
  taglines: [
    "Full Stack Developer | MERN & AI Integrations",
    "Building Scalable & High-Performance Web Apps",
    "MERN Stack Specialist | Backend & APIs Expert",
    "Frontend Developer | React, Tailwind, Modern UI",
    "Backend Developer | Node.js, Django, REST APIs",
    "Python & Django Developer with AI Integrations",
    "Passionate about AI-Driven Web Applications",
    "Turning Ideas into Interactive Digital Solutions",
  ],
  intro:
    "Full Stack Developer with 1.6+ years of experience specializing in Python (Django) and the MERN stack. Skilled at building scalable APIs, intuitive frontends, and integrating AI services to create impactful digital products.",
  email: "kalyanlee3@gmail.com",
  resumeUrl: "/kalyan_resume.pdf",
  socialLinks: {
    github: "https://github.com/Kalyanpandaga",
    linkedin: "https://www.linkedin.com/in/kalyan-pandaga",
    email: "mailto:kalyanlee3@gmail.com",
  },
};

export const aboutInfo = {
  description:
    "I’m a results-driven Full Stack Developer with 1.6+ years of professional experience in backend development using Django REST Framework and strong expertise in building modern full stack applications with the MERN stack. My focus is on crafting scalable APIs, seamless user experiences, and AI-powered solutions that solve real-world challenges. Currently, I’m expanding my skills in advanced Node.js, React, and cloud integrations to stay at the forefront of modern web development.",
  experience: "1.6+ years (Backend) | Growing MERN Expertise",
  focus: "Full Stack Development, AI Integrations, Scalable Architectures",
  location: "India",
};

export const skills = {
  frontend: [
    { name: "React", icon: "FaReact" },
    { name: "JavaScript (ES6+)", icon: "FaJs" },
    { name: "HTML5", icon: "FaHtml5" },
    { name: "CSS3", icon: "FaCss3Alt" },
    { name: "Tailwind CSS", icon: "SiTailwindcss" },
    { name: "React Router", icon: "SiReactrouter" },
  ],
  backend: [
    { name: "Node.js", icon: "FaNodeJs" },
    { name: "Express.js", icon: "SiExpress" },
    { name: "Django ", icon: "SiDjango" },
    { name: "REST APIs", icon: "FaServer" },
    { name: "Python", icon: "FaPython" },
    { name: "Socket.io", icon: "SiSocketdotio" },
  ],
  database: [
    { name: "MongoDB", icon: "SiMongodb" },
    { name: "PostgreSQL", icon: "SiPostgresql" },
    { name: "SQLite", icon: "SiSqlite" },
    { name: "Mongoose ODM", icon: "SiMongodb" },
  ],
};

export const timelineData = [
  {
    year: "2013–2015",
    title: "Intermediate (MPC)",
    description: "Secured 90.1%",
    type: "education",
    icon: "graduation",
  },
  {
    year: "2015–2018",
    title: "BSc MPCs",
    description: "Achieved 73%",
    type: "education",
    icon: "graduation",
  },
  {
    year: "2018–2019",
    title: "Computer Operator",
    description: "Sri Chaitanya Junior College (6 months)",
    type: "work",
    icon: "briefcase",
  },
  {
    year: "2019–2022",
    title: "MCA",
    description: "Achieved 76%",
    type: "education",
    icon: "graduation",
  },
  {
    year: "Sep 2022 – Mar 2024",
    title: "SDE-I",
    description: "NxtWave (18 months)",
    type: "work",
    icon: "briefcase",
  },
  {
    year: "2024 – Present",
    title: "Upskilling & Job Search",
    description: "Focusing on MERN stack and AI integrations",
    type: "learning",
    icon: "rocket",
  },
];

export const projects = {
  fullstack: [
    {
      id: 1,
      name: "AI Mock Interview Platform",
      description:
        "A comprehensive AI-powered platform for personalized interview practice with real-time question generation, intelligent feedback, and progress tracking.",
      features: [
        "Dynamic interview flow with context-aware AI-generated questions",
        "Real-time analysis and actionable feedback to improve performance",
        "Backend APIs built using Python and Django for secure data handling",
        "User authentication, interview history, and progress tracking",
        "Responsive React frontend with smooth navigation and feedback display",
      ],
      techStack: [
        "Python",
        "Django",
        "REST API",
        "React",
        "AI Services (OpenAI)",
        "HTML",
        "CSS",
      ],
      category: "fullstack",
    },
    {
      id: 2,
      name: "DevTinder – Developer Networking Platform",
      description:
        "Full-stack web application enabling developers to connect, collaborate, and chat in real time. Features secure authentication, editable profiles, and real-time messaging for seamless networking.",
      features: [
        "Secure user authentication using JWT with HTTP-only cookies (protection against XSS/CSRF)",
        "Editable developer profiles with live preview (name, avatar, bio, age, gender)",
        "Developer feed to discover profiles and send interest/ignore requests",
        "Connection requests management (accept/reject) to establish connections",
        "Real-time one-to-one chat between connected developers using Socket.IO",
        "Responsive UI with React Router and conditional rendering based on auth state",
        "Deployed on Render with backend-frontend integration and CORS handling",
      ],
      techStack: [
        "React (Vite)",
        "Tailwind CSS / DaisyUI",
        "Redux Toolkit",
        "Node.js",
        "Express.js",
        "MongoDB",
        "Mongoose",
        "Socket.IO",
        "JWT (HTTP-only cookies)",
      ],
      category: "fullstack",
      liveUrl: "https://dev-tinder-qyta.onrender.com",
      githubUrl: "https://github.com/Kalyanpandaga/dev_tinder_frontend",
    },
    {
      id: 3,
      name: "Meds Buddy Check – Medication Management System",
      description:
        "A modern medication tracking platform for patients and caretakers. Provides medication scheduling, daily tracking, and progress monitoring through a clean, user-friendly interface.",
      features: [
        "Separate patient and caretaker roles for tailored experiences",
        "Medication scheduling with reminders and daily status tracking",
        "Progress metrics and calendar-based medication history view",
        "Caretaker dashboard for managing multiple patients and assignments",
        "Responsive UI built with React and TypeScript for seamless usage",
      ],
      techStack: [
        "React (Vite + TypeScript)",
        "Tailwind CSS / DaisyUI",
        "Node.js",
        "Express.js",
        "SQLite",
        "JWT Authentication",
      ],
      category: "fullstack",
      liveUrl: "https://meds-buddy-check-app.onrender.com/",
      githubUrl: "https://github.com/Kalyanpandaga/meds-buddy-check",
    },
    {
      id: 4,
      name: "Project Management Tool",
      description:
        "A full-stack project management application with role-based access for Admin, Manager, and Developer roles. Enables project/task management, team assignments, progress tracking, and commenting with a modern React UI and Node.js backend.",
      features: [
        "Role-based access control with Admin, Manager, and Developer permissions",
        "Project management (create, edit, delete, assign team members, track progress)",
        "Task management (create, assign, deadlines, status updates, commenting)",
        "JWT-based authentication stored in cookies for secure login sessions",
        "Dashboard with task counts, overdue tasks, and project completion metrics",
        "API documentation via Swagger UI and Postman collection",
        "Responsive frontend built with React and Tailwind CSS",
      ],
      techStack: [
        "React",
        "Tailwind CSS",
        "Node.js",
        "Express.js",
        "SQLite (Sequelize ORM)",
        "JWT Authentication",
        "Swagger API Docs",
      ],
      category: "fullstack",
      liveUrl: "https://project-management-tool-1-9214.onrender.com",
      githubUrl: "https://github.com/Kalyanpandaga/project-management-tool",
    },
  ],
  frontend: [
    {
      id: 6,
      name: "Portfolio Website v2",
      description:
        "Modern, responsive portfolio website with smooth animations and dark mode support.",
      features: [
        "Responsive design with mobile-first approach",
        "Smooth scroll animations and transitions",
        "Dark mode toggle functionality",
        "Project filtering and search",
        "Contact form with validation",
      ],
      techStack: [
        "React",
        "TypeScript",
        "Tailwind CSS",
        "Framer Motion",
        "React Hook Form",
      ],
      liveUrl: "https://portfolio-v2.demo",
      githubUrl: "https://github.com/Kalyanpandaga/portfolio-v2",
      category: "frontend",
    },
    {
      id: 7,
      name: "Task Management App",
      description:
        "Productivity-focused task management application with drag-and-drop functionality.",
      features: [
        "Drag and drop task organization",
        "Kanban board interface",
        "Task priority and deadline management",
        "Local storage for data persistence",
        "Keyboard shortcuts for power users",
      ],
      techStack: [
        "React",
        "TypeScript",
        "React DnD",
        "CSS Modules",
        "Local Storage",
      ],
      liveUrl: "https://task-manager.demo",
      githubUrl: "https://github.com/Kalyanpandaga/task-manager",
      category: "frontend",
    },
    {
      id: 8,
      name: "Weather Dashboard",
      description:
        "Beautiful weather application with detailed forecasts and location-based services.",
      features: [
        "Current weather and 7-day forecast",
        "Location-based weather detection",
        "Interactive weather maps",
        "Weather alerts and notifications",
        "Beautiful animated weather icons",
      ],
      techStack: [
        "React",
        "OpenWeather API",
        "Chart.js",
        "Geolocation API",
        "CSS3",
      ],
      liveUrl: "https://weather-dashboard.demo",
      githubUrl: "https://github.com/Kalyanpandaga/weather-dashboard",
      category: "frontend",
    },
    {
      id: 9,
      name: "Recipe Finder App",
      description:
        "Recipe discovery platform with ingredient-based search and meal planning.",
      features: [
        "Recipe search by ingredients",
        "Meal planning and shopping lists",
        "Nutritional information display",
        "Recipe saving and favorites",
        "Cooking timer and step-by-step guide",
      ],
      techStack: [
        "React",
        "Recipe API",
        "Context API",
        "CSS Grid",
        "Local Storage",
      ],
      liveUrl: "https://recipe-finder.demo",
      githubUrl: "https://github.com/Kalyanpandaga/recipe-finder",
      category: "frontend",
    },
    {
      id: 10,
      name: "Music Player App",
      description:
        "Spotify-inspired music player with playlist management and audio visualization.",
      features: [
        "Audio playback with custom controls",
        "Playlist creation and management",
        "Audio visualization with Web Audio API",
        "Responsive design for mobile devices",
        "Local music file support",
      ],
      techStack: [
        "React",
        "Web Audio API",
        "CSS3",
        "HTML5 Audio",
        "Context API",
      ],
      liveUrl: "https://music-player.demo",
      githubUrl: "https://github.com/Kalyanpandaga/music-player",
      category: "frontend",
    },
    {
      id: 11,
      name: "Crypto Tracker",
      description:
        "Real-time cryptocurrency tracking application with portfolio management.",
      features: [
        "Real-time crypto price tracking",
        "Portfolio management and P&L calculation",
        "Price alerts and notifications",
        "Historical price charts",
        "Market news and analysis",
      ],
      techStack: ["React", "CoinGecko API", "Chart.js", "Context API", "CSS3"],
      liveUrl: "https://crypto-tracker.demo",
      githubUrl: "https://github.com/Kalyanpandaga/crypto-tracker",
      category: "frontend",
    },
  ],
  backend: [
    {
      id: 12,
      name: "Kalyan Weekly SMS Workflow",
      description:
        "Automated CRM SMS system for customer engagement and communication workflows.",
      features: [
        "Automated SMS scheduling and delivery",
        "Customer segmentation and targeting",
        "SMS template management",
        "Delivery tracking and analytics",
        "Integration with CRM systems",
      ],
      techStack: [
        "Django",
        "Django REST Framework",
        "Celery",
        "PostgreSQL",
        "SMS Gateway API",
      ],
      liveUrl: "https://sms-workflow.demo",
      githubUrl: "https://github.com/Kalyanpandaga/sms-workflow",
      category: "backend",
    },
    {
      id: 13,
      name: "Authentication Microservice",
      description:
        "Scalable authentication service with JWT tokens and role-based access control.",
      features: [
        "JWT-based authentication system",
        "Role-based access control (RBAC)",
        "Password encryption and security",
        "API rate limiting and throttling",
        "Email verification and password reset",
      ],
      techStack: [
        "Node.js",
        "Express",
        "MongoDB",
        "JWT",
        "Bcrypt",
        "Nodemailer",
      ],
      liveUrl: "https://auth-service.demo",
      githubUrl: "https://github.com/Kalyanpandaga/auth-microservice",
      category: "backend",
    },
    {
      id: 14,
      name: "File Upload Service",
      description:
        "Robust file upload and management service with cloud storage integration.",
      features: [
        "Multi-file upload with progress tracking",
        "Cloud storage integration (AWS S3)",
        "File type validation and security",
        "Image resizing and optimization",
        "RESTful API with comprehensive documentation",
      ],
      techStack: ["Node.js", "Express", "Multer", "AWS S3", "Sharp", "MongoDB"],
      liveUrl: "https://file-service.demo",
      githubUrl: "https://github.com/Kalyanpandaga/file-upload-service",
      category: "backend",
    },
    {
      id: 15,
      name: "Real-time Chat API",
      description:
        "WebSocket-based chat service with room management and message persistence.",
      features: [
        "Real-time messaging with Socket.io",
        "Chat room creation and management",
        "Message history and persistence",
        "User presence and typing indicators",
        "Message encryption and security",
      ],
      techStack: ["Node.js", "Express", "Socket.io", "MongoDB", "Redis", "JWT"],
      liveUrl: "https://chat-api.demo",
      githubUrl: "https://github.com/Kalyanpandaga/chat-api",
      category: "backend",
    },
    {
      id: 16,
      name: "Email Automation System",
      description:
        "Comprehensive email marketing and automation platform with template management.",
      features: [
        "Email template builder and editor",
        "Automated email campaigns",
        "Subscriber management and segmentation",
        "Email analytics and tracking",
        "SMTP configuration and delivery optimization",
      ],
      techStack: [
        "Django",
        "Celery",
        "PostgreSQL",
        "Redis",
        "HTML Email Templates",
      ],
      liveUrl: "https://email-automation.demo",
      githubUrl: "https://github.com/Kalyanpandaga/email-automation",
      category: "backend",
    },
    {
      id: 17,
      name: "Payment Gateway Integration",
      description:
        "Secure payment processing system with multiple gateway support and transaction management.",
      features: [
        "Multi-gateway payment processing",
        "Webhook handling and verification",
        "Transaction logging and reconciliation",
        "Refund and chargeback management",
        "PCI compliance and security measures",
      ],
      techStack: [
        "Node.js",
        "Express",
        "Stripe API",
        "PayPal API",
        "MongoDB",
        "Crypto",
      ],
      liveUrl: "https://payment-gateway.demo",
      githubUrl: "https://github.com/Kalyanpandaga/payment-gateway",
      category: "backend",
    },
  ],
};
